import { NextResponse } from 'next/server';
import { registerSchema } from '@/lib/validators';
import { getDb } from '@/lib/db';
import { hashPassword } from '@/lib/auth';
import { User } from '@/types';
import { findBestDoctorForCondition } from '@/lib/doctorAssignment';

export async function POST(request: Request) {
  try {
    const db = getDb();
    const body = await request.json();
    const result = registerSchema.safeParse(body);
    
    if (!result.success) {
      return NextResponse.json({ error: 'Invalid input', details: result.error.flatten().fieldErrors }, { status: 400 });
    }
    
    const { email, password, full_name, role, specialization, primary_condition } = result.data;

    const existingUser = db.prepare('SELECT * FROM users WHERE email = ?').get(email) as User | undefined;
    if (existingUser) {
      return NextResponse.json({ error: 'Email already exists' }, { status: 409 });
    }

    const password_hash = await hashPassword(password);

    // Resolve the best doctor before the transaction (uses prepare/get, safe outside tx)
    const assignedDoctor = role === 'patient' && primary_condition
      ? findBestDoctorForCondition(primary_condition)
      : null;

    const insertTransaction = db.transaction(() => {
      let stmt;
      if (role === 'doctor') {
        stmt = db.prepare('INSERT INTO users (email, password_hash, full_name, role, specialization) VALUES (?, ?, ?, ?, ?)');
        stmt.run(email, password_hash, full_name, role, specialization);
      } else {
        stmt = db.prepare('INSERT INTO users (email, password_hash, full_name, role) VALUES (?, ?, ?, ?)');
        stmt.run(email, password_hash, full_name, role);
      }
      // users.id is a TEXT hex string generated by SQLite default, not an integer rowid
      const newRow = db.prepare('SELECT id FROM users WHERE email = ?').get(email) as { id: string };
      const userId = newRow.id;
      if (role === 'patient') {
        db.prepare('INSERT INTO patients (user_id, conditions) VALUES (?, ?)').run(userId, primary_condition ?? null);
        if (assignedDoctor) {
          db.prepare('UPDATE patients SET assigned_doctor_id = ? WHERE user_id = ?').run(assignedDoctor.id, userId);
        } else {
          // Fallback: assign first available active doctor
          const fallback = db.prepare("SELECT id FROM users WHERE role = 'doctor' AND is_active = 1 LIMIT 1").get() as { id: string } | undefined;
          if (fallback) {
            db.prepare('UPDATE patients SET assigned_doctor_id = ? WHERE user_id = ?').run(fallback.id, userId);
          }
        }
      }
      return userId;
    });

    const newUserId = insertTransaction();
    
    const newUser = db.prepare('SELECT id, email, full_name, role, is_active FROM users WHERE id = ?').get(newUserId) as User;
    
    return NextResponse.json({ user: newUser }, { status: 201 });
  } catch (error) {
    console.error('Register error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
